---
title: "DoubletFinder"
author: "Nathan Ewing-Crystal"
date: "2023-05-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
***
Doubletfinder
https://github.com/chris-mcginnis-ucsf/DoubletFinder

Note - not using multiplexing, assuming "no ground truth"
Investigate Fib_1/Fib_2
Using sobject.sub.fib
***
```{r}
library(Seurat)
library(ggplot2)

#remotes::install_github('chris-mcginnis-ucsf/DoubletFinder')
library("DoubletFinder")
```

```{r}
#Specify your preferred directory for all input + output
dir = "/Users/nathanewing-crystal/Ari Molofsky Lab Dropbox/Ari Molofsky Lab Team Folder/Nathan Ewing-Crystal/RNASeq/Lesion snRNASeq 2 Tgfb/seurat"
#Specify exactly where your seurat files live
datafolder = "Data/Seurat"

project<-"tgfb_lesion_snRNASeq"  

Plotfolder = "Plots/Fibroblast Subset"
iterationname = "fib_reclustered"

#load sobj.sub.fib
load(file.choose())
```

```{r}
sobj_doublets = sobject.sub.fib
DefaultAssay(sobj_doublets) = "SCT"

#below code from DoubletFinder README example code

## pK Identification (no ground-truth)
sweep.res.list <- paramSweep(sobj_doublets, PCs = 1:30, sct = TRUE)
sweep.stats <- summarizeSweep(sweep.res.list, GT = FALSE)
bcmvn <- find.pK(sweep.stats)

#select max
bcmvn$pK[which.max(bcmvn$BCmetric)]
pk = 0.3

## Homotypic Doublet Proportion Estimate
homotypic.prop <- modelHomotypic(sobj_doublets$celltype)

percent_multi = c(0.08)
# [based on 10x multiplet formation guide]
nExp_poi <- round(percent_multi*nrow(sobj_doublets@meta.data))  

nExp_poi.adj <- round(nExp_poi*(1-homotypic.prop))

## Run DoubletFinder 
sobj_doublets <- doubletFinder(sobj_doublets, PCs = 1:30, pN = 0.25, pK = pk, nExp = nExp_poi.adj, reuse.pANN = FALSE, sct = TRUE)

DimPlot(sobj_doublets, group.by = "celltype", label = T)
DimPlot(sobj_doublets, group.by = "DF.classifications_0.25_0.3_812")

```

