---
title: "Integrate"
author: "Nathan Ewing-Crystal"
date: "2023-05-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# install.packages("devtools")
options(timeout = 600000000) ### set this to avoid timeout error
devtools::install_github("dmcable/spacexr", build_vignettes = FALSE)
library(Seurat)
library(spacexr)
library(Matrix)
library(ggplot2)
library(gridExtra)
library(RColorBrewer)
```

```{r}
#Specify your preferred directory for all input + output
dir = "/Users/nathanewing-crystal/Dropbox (Ari Molofsky Lab)/Ari Molofsky Lab Team Folder/Nathan Ewing-Crystal/RNASeq/Lesion snRNASeq/seurat"

#Specify exactly where your matrix files/raw data live
datafolder = "Data/Seurat"
Plotfolder = "Plots"
project<-"lesion_snRNASeq"
#load snRNASeq, Visium objects
load(file.choose())
```

#load "lesion_snRNASeq_final_immune.RData" and proceed to below
#contains fibtype and lesiontype, doublet clusters 7/10 removed
#After 11_astrocyte_subset - transfer "astrotype" and "astrotypecluster" metadata
```{r}
celltype = as.character(sobject$celltype)
names(celltype) = as.character(colnames(sobject))

celltypecluster = as.character(sobject$celltypecluster)
names(celltypecluster) = as.character(colnames(sobject))

astrotype = as.character(sobject.sub.astro$astrotype)
names(astrotype) = as.character(colnames(sobject.sub.astro))

astrotypecluster = as.character(sobject.sub.astro$astrotypecluster)
names(astrotypecluster) = as.character(colnames(sobject.sub.astro))

for(cell in names(celltype)){
  if(cell %in% names(astrotype)){
      index_cell = which(names(celltype) == cell)
      index_astro = which(names(astrotype) == cell)
      celltype[index_cell] = paste0("Astrocyte_", astrotype[index_astro])
      celltypecluster[index_cell] = paste0("Astrocyte_", astrotypecluster[index_astro])
  }
}

sobject$astrotype = celltype
sobject$astrotypecluster = celltypecluster

Idents(sobject) = "astrotype"

iterationname = "final_astro"

save(sobject,file = file.path(dir,datafolder,paste0(project,"_",iterationname,".RData")))
```

#Next, exclude meninges - by microanatomy
```{r}
iterationname = "final_astro_nomen_wt"

Idents(sobject) = "microanatomy"
sobject.nomen = subset(sobject, idents = c("Lesion", "Parenchyma"))
rm(sobject)

Idents(sobject.nomen) = "genotype"
sobject.nomen.wt = subset(sobject.nomen, idents = "WT")

rm(sobject.nomen)
save(sobject.nomen.wt,file = file.path(dir,datafolder,paste0(project,"_",iterationname,".RData")))
```
#optionally, load "sobject_final_astro_nomen_wt" 
#for below code, use "sobject.nomen.wt", but called "sobject"
```{r}
sobject = sobject.nomen.wt
rm(sobject.nomen.wt)

Idents(sobject) = "astrotype"
#remove cluster xx if insufficient #'s for algorithm
remove = levels(Idents(sobject))
remove = remove[!(remove %in% c("Neural Progenitors"))]
sobject = subset(sobject, idents = remove)
```

```{r}
anchors <- FindTransferAnchors(reference = sobject, query = vobj.merge.sub10, normalization.method = "SCT", reference.assay = "SCT", query.assay = "SCT")
predictions.assay <- TransferData(anchorset = anchors, refdata = sobject$astrotype, prediction.assay = TRUE, dims = c(1:30), weight.reduction = vobj.merge.sub10[["pca"]])
vobj.merge.sub10[["predictions_integrate"]] <- predictions.assay
DefaultAssay(vobj.merge.sub10) <- "predictions_integrate"
```

```{r}
image1 = "A.Rest.2dpi"
image2 = "B.7dpi"
image3 = "C.21dpi"
```


```{r}
#Extract snRNASeq counts to construct reference
counts = sobject@assays$RNA@counts
cell_types = as.factor(sobject$astrotype)

# Create the Reference object
reference <- Reference(counts, cell_types)
print(dim(reference@counts)) #observe Digital Gene Expression matrix
table(reference@cell_types) #number of occurences for each cell type

datafolder_up = "Data"
saveRDS(reference, file.path(dir, datafolder_up,'SCRef_astro.rds'))

```

```{r}
coords1 = vobj.merge.sub10@images$A.Rest.2dpi@coordinates[,5:4]
coords2 = vobj.merge.sub10@images$B.7dpi@coordinates[,5:4]
coords3 = vobj.merge.sub10@images$C.21dpi@coordinates[,5:4]

counts = vobj.merge.sub10@assays$Spatial@counts

# Create SpatialRNA object
puck1 <- SpatialRNA(coords1, counts)
puck2 <- SpatialRNA(coords2, counts)
puck3 <- SpatialRNA(coords3, counts)

spatial.replicates <- list(puck1, puck2, puck3)
replicate_names <- c('Rest.2dpi','7dpi','21dpi')
rctd <- create.RCTD.replicates(spatial.replicates, reference, replicate_names, max_cores = 1)
rctd <- run.RCTD.replicates(rctd, doublet_mode = 'full')
saveRDS(rctd, file.path(dir, datafolder_up,'rctd_astro.rds'))

# Create the output directory in your working directory
resultsdir = file.path(dir, Plotfolder, "visium/Astrocyte/")


# Create variables from the myRCTD object to plot results
barcodes1 = colnames(rctd@RCTD.reps[[1]]@spatialRNA@counts)
barcodes2 = colnames(rctd@RCTD.reps[[2]]@spatialRNA@counts)
barcodes3 = colnames(rctd@RCTD.reps[[3]]@spatialRNA@counts) # list of spatial barcodes
barcodes = list(barcodes1, barcodes2, barcodes3)

weights1 <- rctd@RCTD.reps[[1]]@results$weights
weights2 <- rctd@RCTD.reps[[2]]@results$weights
weights3 <- rctd@RCTD.reps[[3]]@results$weights # Weights for each cell type per barcode

# Normalize per spot weights so cell type probabilities sum to 1 for each spot
norm_weights1 <- normalize_weights(weights1) 
norm_weights2 <- normalize_weights(weights2) 
norm_weights3 <- normalize_weights(weights3) 
norm_weights = list(norm_weights1, norm_weights2, norm_weights3)

cell_type_names<-colnames(norm_weights1) # List of cell types [same for all 3]
# For each spot barcode (row), you can see the normalized weight for each cell type (column)

#note - different cell type names (dash instead of underscore) for integration
cell_type_names_dash = rownames(vobj.merge.sub10@assays$predictions_integrate)

# Plot cell type probabilities (normalized) per spot (red = 1, blue = 0 probability)
# Different order in cell_type_names and cell_type_names_dash, but doesn't matter - save with correct filename
for(i in 1:length(cell_type_names_dash)){
    if(i > length(cell_type_names)){print(paste0("skip ", i))} else{
    max1 = plyr::round_any(max(rctd@RCTD.reps[[1]]@results$weights[,cell_type_names[i]]), accuracy = 0.1, f = ceiling) #take maximum prediction, round up to nearest 0.1 (easier to view)
    max2 = plyr::round_any(max(rctd@RCTD.reps[[2]]@results$weights[,cell_type_names[i]]), accuracy = 0.1, f = ceiling) #take maximum prediction, round up to nearest 0.1 (easier to view)
    max3 = plyr::round_any(max(rctd@RCTD.reps[[3]]@results$weights[,cell_type_names[i]]), accuracy = 0.1, f = ceiling) #take maximum prediction, round up to nearest 0.1 (easier to view)
    max = max(max1, max2, max3)
    
    j=1
    p1 = plot_puck_continuous(rctd@RCTD.reps[[j]]@spatialRNA, 
                       barcodes[[j]],
                       norm_weights[[j]][,cell_type_names[i]],
                       title =cell_type_names[i], 
                       size=1,
                       ylimit = c(0, max))
    j=2
    p2 = plot_puck_continuous(rctd@RCTD.reps[[j]]@spatialRNA, 
                       barcodes[[j]],
                       norm_weights[[j]][,cell_type_names[i]],
                       title =cell_type_names[i], 
                       size=1,
                       ylimit = c(0, max))
    j=3
    p3 = plot_puck_continuous(rctd@RCTD.reps[[j]]@spatialRNA, 
                       barcodes[[j]],
                       norm_weights[[j]][,cell_type_names[i]],
                       title =cell_type_names[i], 
                       size=1,
                       ylimit = c(0, max))
    }
    p4 = SpatialFeaturePlot(vobj.merge.sub10, images = c(image1, image2, image3), features = cell_type_names_dash[i])
    
    if(i > length(cell_type_names)){print(paste0("skip save ", i))} else{
    setEPS()
    postscript(file.path(resultsdir,paste0(cell_type_names[i], "_spacexr_deconv.eps")), width = 12)
    print(grid.arrange(p1, p2, p3, ncol = 3))
    dev.off()
    }
    
    setEPS()
    postscript(file.path(resultsdir,paste0(cell_type_names_dash[i], "_integration_prediction.eps")))
    print(p4)
    dev.off()
}

#now add back to Visium and plot

#fill in image4
rownames_image4 = colnames(vobj.merge.sub10)[vobj.merge.sub10$orig.ident == "21dpi Deleter"]
empty_image4 = matrix(0, nrow = length(rownames_image4), ncol = length(cell_type_names))
rownames(empty_image4) = rownames_image4
colnames(empty_image4) = cell_type_names
#fill in missing spots from 21dpi (unknown origin)
normweights_seurat = rbind(norm_weights1, norm_weights2, norm_weights3, empty_image4)
rownames_missing = colnames(vobj.merge.sub10)[(!(colnames(vobj.merge.sub10) %in% rownames(normweights_seurat)))]
missing = matrix(0, nrow = length(rownames_missing), ncol = length(cell_type_names))
rownames(missing) = rownames_missing
colnames(missing) = cell_type_names
#bind together
normweights_seurat = rbind(norm_weights1, norm_weights2, norm_weights3, empty_image4, missing)
normweights_seurat = as.matrix(t(normweights_seurat))

vobj.merge.sub10[["celltype_spacexr_astro"]] <- CreateAssayObject(data = normweights_seurat)
DefaultAssay(vobj.merge.sub10) = "celltype_spacexr_astro"
Plotfolder = "Plots/visium/Astrocyte/plot_visium"
for(celltype in rownames(vobj.merge.sub10)){
  
  #EQUALIZE SCALE BETWEEN 3 SECTIONS
  rng = range(FetchData(vobj.merge.sub10, vars = celltype)) #a range to have the same min and max for both plots

  myPalette <- colorRampPalette(rev(brewer.pal(11, "Spectral")))
  sc <- scale_fill_gradientn(colours = myPalette(100), limits = c(rng[1], rng[2]), breaks = c(0, round(max(rng)/2, digits = 2), round(max(rng), digits = 2)))
  
  p1 = SpatialFeaturePlot(vobj.merge.sub10, celltype, images = c(image1, image2, image3))
  
  setEPS()
  postscript(file.path(dir, Plotfolder, paste0(celltype, "_spacexr_deconv_plot_visium.eps")))
  print(p1[[1]] + sc + p1[[2]] + sc + p1[[3]] + sc)
  dev.off()
}
```
```{r}
save(vobj.merge.sub10,file = file.path(dir, datafolder,paste0(project,"_vobj.merge.sub10_snseq",iterationname,".RData")))

```


