---
title: "Plots"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("BiocManager")
#BiocManager::install("Seurat")
#BiocManager::install("ggplot2")
#BiocManager::install("sctransform")

library(Seurat)
library(ggplot2)
library(dplyr)
library(ape)
library(cowplot)
library(Matrix)
library(EnhancedVolcano)
library(knitr)
library(readr)
library(RColorBrewer)

#Specify your preferred directory for all input + output
dir = "/Users/nathanewing-crystal/Ari Molofsky Lab Dropbox/Ari Molofsky Lab Team Folder/Nathan Ewing-Crystal/RNASeq/Lesion snRNASeq 2 Tgfb/seurat"
#Specify exactly where your seurat files live
datafolder = "Data/Seurat"

project<-"tgfb_lesion_snRNASeq"  

#set up folders
Plotfolder = "Plots"
load(file.choose())
```

Barplot for any two (or more) categories

```{r}
#Pick metadata columns
clustercolumn = "fibtype"
samplecolumn = "condition"
#pick a reasonable number of cells per sample to normalize by
ncells = 2000 
cols = brewer.pal(n = 6, name = "Dark2")
cols.4 = brewer.pal(n=4, name = "Dark2")
cols.3 = brewer.pal(n=3, name = "Dark2")
cols.2 = c("#1B9E77", "#D95F02")

#If you want to only compare particular samples/conditions, split further by another metadata column: 
# split = NULL
```

```{r}
# Below uses total sobject
# measure fibroblast subsets across timepoints as % of a) total cells or b) lesion
sobject_sub = sobject
clustercolumn = "fibtype"
  
  #Make a table and normalize
  r = table(sobject_sub[[clustercolumn]][,1],sobject_sub[[samplecolumn]][,1])
    
    t = r  
    #remove any clusters that don't have cells
    t = t[rowSums(t)>0,]
    
    #normalize by sample
    t = apply(t,MARGIN = 2,function(x)x/sum(x))
    t = round(t*ncells,0)
    
    #convert to percents for each *sample*
    t = apply(t,MARGIN = 2,function(x)x/sum(x))
    t = round(t*100,2)
    
    #reorder (by condition)
    tdf = as.data.frame(t)
    tdf = tdf[,c("WT", "cKO", "ADWA11")]
    t = tdf
    
    clusters_to_keep = c("Fibroblast_Prolif", "Fibroblast_Myofibroblast", "Fibroblast_ex-Myofibroblast",  "Fibroblast_Altered-dural_immune", "Fibroblast_Arachnoid",  "Fibroblast_Pial")
    t = t[clusters_to_keep,]

    name = paste0(project,"_", "_cluster-frequencies_of_total")
    
    setEPS()
    postscript(file.path(dir,"Plots/Barplots",paste0(name,"barplot.eps")))
    barplot(t(t), main="Sample composition by cluster",
         ylab = "% of sample", col=cols.3,axisnames = T,
          width = .2, cex.names = 0.7,axis.lty = 1, las=2, mgp=c(), beside=TRUE)
    title(xlab = "Cluster", line = 4)
    legend("topright", legend=rownames(t(t)), fill=cols.3, bg="white", inset=c(0.75, 0.02))
    dev.off()
  
    print(barplot(t(t), main="Sample composition by cluster",
         ylab = "% of sample", col=cols.3,axisnames = T,
          width = .2, cex.names = 0.7,axis.lty = 1, las=2, mgp=c(), beside=TRUE))
    title(xlab = "Cluster", line = 4)
    legend("topright", legend=rownames(t(t)), fill=cols.3, bg="white", inset=c(0.75, 0.02))
    
#for pie charts
    
    t = r  
    #remove any clusters that don't have cells
    t = t[rowSums(t)>0,]
    
    #normalize by sample
    t = apply(t,MARGIN = 2,function(x)x/sum(x))
    t = round(t*ncells,0)
    
    #convert to percents for each cluster
    t = apply(t,MARGIN = 1,function(x)x/sum(x))
    t = round(t*100,2)
    
    #reorder (by condition)
    tdf = as.data.frame(t)
    tdf = tdf[c("WT", "cKO", "ADWA11"),]
    t = tdf
    
    clusters_to_keep = c("Fibroblast_Prolif", "Fibroblast_Myofibroblast", "Fibroblast_ex-Myofibroblast",  "Fibroblast_Altered-dural_immune", "Fibroblast_Arachnoid",  "Fibroblast_Pial")
    t = t[,clusters_to_keep]
```

#just cko wt
```{r}
# Below uses total sobject
# measure immune subsets across timepoints as % of a) total cells or b) lesion
sobject_sub = sobject
clustercolumn = "immunetype"
  
  #Make a table and normalize
  r = table(sobject_sub[[clustercolumn]][,1],sobject_sub[[samplecolumn]][,1])
    
    t = r  
    #remove any clusters that don't have cells
    t = t[rowSums(t)>0,]
    
    #normalize by sample
    t = apply(t,MARGIN = 2,function(x)x/sum(x))
    t = round(t*ncells,0)
    
    #convert to percents for each *sample*
    t = apply(t,MARGIN = 2,function(x)x/sum(x))
    t = round(t*100,2)
    
    #reorder (by condition)
    tdf = as.data.frame(t)
    tdf = tdf[,c("WT", "cKO")]
    t = tdf
    
    clusters_to_keep = c("Immune_Microglia", "Immune_Monocytes_DCs", "Immune_DAMs", "Immune_SAMs", "Immune_PVMs", "Immune_Prolif", "Immune_Mac_other")
    t = t[clusters_to_keep,]

    name = paste0(project,"_", "MYELOID_cluster-frequencies_of_total_noADWA11")
    
    setEPS()
    postscript(file.path(dir,"Plots/Barplots",paste0(name,"barplot.eps")))
    barplot(t(t), main="Sample composition by cluster",
         ylab = "% of sample", col=cols.2,axisnames = T,
          width = .2, cex.names = 0.7,axis.lty = 1, las=2, mgp=c(), beside=TRUE)
    title(xlab = "Cluster", line = 4)
    legend("topright", legend=rownames(t(t)), fill=cols.2, bg="white", inset=c(0.75, 0.02))
    dev.off()
  
    print(barplot(t(t), main="Sample composition by cluster",
         ylab = "% of sample", col=cols.2,axisnames = T,
          width = .2, cex.names = 0.7,axis.lty = 1, las=2, mgp=c(), beside=TRUE))
    title(xlab = "Cluster", line = 4)
    legend("topright", legend=rownames(t(t)), fill=cols.3, bg="white", inset=c(0.75, 0.02))
    
    #for pie charts
    
    t = r  
    #remove any clusters that don't have cells
    t = t[rowSums(t)>0,]
    
    #normalize by sample
    t = apply(t,MARGIN = 2,function(x)x/sum(x))
    t = round(t*ncells,0)
    
    #convert to percents for each cluster
    t = apply(t,MARGIN = 1,function(x)x/sum(x))
    t = round(t*100,2)
    
    #reorder (by condition)
    tdf = as.data.frame(t)
    tdf = tdf[c("WT", "cKO"),]
    t = tdf
    
    clusters_to_keep = c("Immune_Microglia", "Immune_Monocytes_DCs", "Immune_DAMs", "Immune_SAMs", "Immune_PVMs", "Immune_Prolif", "Immune_Mac_other")
    t = t[,clusters_to_keep]
```